<?php

/**  
 *Plugin Name: GitHub API
 *description: Add GitHub project information using shortcode
 *Version: 1.0
 *Author: Your Name
 *License: GPLv2 or later
 *Text Domain: github-api
 */

defined('ABSPATH') or die('No script kiddies please!');

require_once 'vendor/autoload.php';
require_once 'response.php';
require_once 'polymorphism.php';

/**
 * Generated by the WordPress Option Page generator
 * at http://jeremyhixon.com/wp-tools/option-page/
 */

class GithubAPI {
	private $github_api_options;

	public function __construct() {
		add_action('admin_menu', array($this, 'github_api_add_plugin_page'));
		add_action('admin_init', array($this, 'github_api_page_init'));
	}

	public function github_api_add_plugin_page() {
		add_menu_page(
			'Github API', // page_title
			'Github API', // menu_title
			'manage_options', // capability
			'github-api', // menu_slug
			array($this, 'github_api_create_admin_page'), // function
			'dashicons-admin-generic', // icon_url
			2 // position
		);
	}

	public function github_api_create_admin_page() {
		$this->github_api_options = get_option('github_api_option_name'); ?>

		<div class="wrap">
			<h2>Github API</h2>
			<p>Hello World</p>
			<?php settings_errors(); ?>

			<form method="post" action="options.php">
				<?php
				settings_fields('github_api_option_group');
				do_settings_sections('github-api-admin');
				submit_button();
				?>
			</form>
		</div>
	<?php }

	public function github_api_page_init() {
		register_setting(
			'github_api_option_group', // option_group
			'github_api_option_name', // option_name
			array($this, 'github_api_sanitize') // sanitize_callback
		);

		add_settings_section(
			'github_api_setting_section', // id
			'Settings', // title
			array($this, 'github_api_section_info'), // callback
			'github-api-admin' // page
		);

		add_settings_field(
			'label_0', // id
			'Label', // title
			array($this, 'label_0_callback'), // callback
			'github-api-admin', // page
			'github_api_setting_section' // section
		);

		add_settings_field(
			'label_1', // id
			'Label', // title
			array($this, 'label_1_callback'), // callback
			'github-api-admin', // page
			'github_api_setting_section' // section
		);

		add_settings_field(
			'fav_food_2', // id
			'Fav Food', // title
			array($this, 'fav_food_2_callback'), // callback
			'github-api-admin', // page
			'github_api_setting_section' // section
		);

		add_settings_field(
			'fav_food_3', // id
			'Fav Food', // title
			array($this, 'fav_food_3_callback'), // callback
			'github-api-admin', // page
			'github_api_setting_section' // section
		);

		add_settings_field(
			'fav_food_4', // id
			'Fav Food', // title
			array($this, 'fav_food_4_callback'), // callback
			'github-api-admin', // page
			'github_api_setting_section' // section
		);
	}

	public function github_api_sanitize($input) {
		$sanitary_values = array();
		if (isset($input['label_0'])) {
			$sanitary_values['label_0'] = sanitize_text_field($input['label_0']);
		}

		if (isset($input['label_1'])) {
			$sanitary_values['label_1'] = esc_textarea($input['label_1']);
		}

		if (isset($input['fav_food_2'])) {
			$sanitary_values['fav_food_2'] = $input['fav_food_2'];
		}

		if (isset($input['fav_food_3'])) {
			$sanitary_values['fav_food_3'] = $input['fav_food_3'];
		}

		if (isset($input['fav_food_4'])) {
			$sanitary_values['fav_food_4'] = $input['fav_food_4'];
		}

		return $sanitary_values;
	}

	public function github_api_section_info() {
	}

	public function label_0_callback() {
		printf(
			'<input class="regular-text" type="text" name="github_api_option_name[label_0]" id="label_0" value="%s">',
			isset($this->github_api_options['label_0']) ? esc_attr($this->github_api_options['label_0']) : ''
		);
	}

	public function label_1_callback() {
		printf(
			'<textarea class="large-text" rows="5" name="github_api_option_name[label_1]" id="label_1">%s</textarea>',
			isset($this->github_api_options['label_1']) ? esc_attr($this->github_api_options['label_1']) : ''
		);
	}

	public function fav_food_2_callback() {
	?> <select name="github_api_option_name[fav_food_2]" id="fav_food_2">
			<?php $selected = (isset($this->github_api_options['fav_food_2']) && $this->github_api_options['fav_food_2'] === 'Apple') ? 'selected' : ''; ?>
			<option <?php echo $selected; ?>>Apple</option>
			<?php $selected = (isset($this->github_api_options['fav_food_2']) && $this->github_api_options['fav_food_2'] === 'Lemon') ? 'selected' : ''; ?>
			<option <?php echo $selected; ?>>Lemon</option>
			<?php $selected = (isset($this->github_api_options['fav_food_2']) && $this->github_api_options['fav_food_2'] === 'Water') ? 'selected' : ''; ?>
			<option <?php echo $selected; ?>>Water</option>
		</select> <?php
			}

			public function fav_food_3_callback() {
				printf(
					'<input type="checkbox" name="github_api_option_name[fav_food_3]" id="fav_food_3" value="fav_food_3" %s> <label for="fav_food_3">Banana</label>',
					(isset($this->github_api_options['fav_food_3']) && $this->github_api_options['fav_food_3'] === 'fav_food_3') ? 'checked' : ''
				);
			}

			public function fav_food_4_callback() {
				?> <fieldset><?php $checked = (isset($this->github_api_options['fav_food_4']) && $this->github_api_options['fav_food_4'] === 'Apple') ? 'checked' : ''; ?>
			<label for="fav_food_4-0"><input type="radio" name="github_api_option_name[fav_food_4]" id="fav_food_4-0" value="Apple" <?php echo $checked; ?>> Apple</label><br>
			<?php $checked = (isset($this->github_api_options['fav_food_4']) && $this->github_api_options['fav_food_4'] === 'Lemon') ? 'checked' : ''; ?>
			<label for="fav_food_4-1"><input type="radio" name="github_api_option_name[fav_food_4]" id="fav_food_4-1" value="Lemon" <?php echo $checked; ?>> Lemon</label><br>
			<?php $checked = (isset($this->github_api_options['fav_food_4']) && $this->github_api_options['fav_food_4'] === 'Water') ? 'checked' : ''; ?>
			<label for="fav_food_4-2"><input type="radio" name="github_api_option_name[fav_food_4]" id="fav_food_4-2" value="Water" <?php echo $checked; ?>> Water</label>
		</fieldset> <?php
			}
		}
		if (is_admin())
			$github_api = new GithubAPI();

/* 
 * Retrieve this value with:
 * $github_api_options = get_option( 'github_api_option_name' ); // Array of All Options
 * $label_0 = $github_api_options['label_0']; // Label
 * $label_1 = $github_api_options['label_1']; // Label
 * $fav_food_2 = $github_api_options['fav_food_2']; // Fav Food
 * $fav_food_3 = $github_api_options['fav_food_3']; // Fav Food
 * $fav_food_4 = $github_api_options['fav_food_4']; // Fav Food
 */
